spring:
  application:
    name: product-service
  profiles:
    active: dev
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  servlet:
    context-path: /store/api/v1
  port: 9050
